const API='https://dlmm.datapi.meteora.ag';
const POOLS_API=`${API}/pools`;
const HISTORY_TTL=15*60*1000;
const HISTORY_LIMIT=30;
const DEFAULT_WEIGHTS={multiday:{fee:25,vol:15,tvl:15,price:15,age:15,mc:5,stability:10},newrisk:{fee:30,vol:30,tvl:10,price:10,age:5,mc:5,stability:10}};
const state={pools:[],window:'2h',mode:'multiday',weights:JSON.parse(JSON.stringify(DEFAULT_WEIGHTS)),history:{},apiHistory:{},historyLoading:false};
const $=id=>document.getElementById(id), clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const fmtUSD=n=>{if(!Number.isFinite(n))return '—';if(Math.abs(n)>=1e9)return '$'+(n/1e9).toFixed(2)+'B';if(Math.abs(n)>=1e6)return '$'+(n/1e6).toFixed(2)+'M';if(Math.abs(n)>=1e3)return '$'+(n/1e3).toFixed(1)+'K';return '$'+n.toFixed(0)};
const fmtPct=n=>Number.isFinite(n)?(n>=0?'+':'')+n.toFixed(2)+'%':'—';
function pick(o,keys,def=null){for(const k of keys){if(o&&o[k]!==undefined&&o[k]!==null&&o[k]!=='')return o[k]}return def}
function num(v){if(typeof v==='number')return v;if(v===null||v===undefined)return NaN;return Number(String(v).replace(/[$,%]/g,'').replace(/,/g,''))}
function hours(v){if(Number.isFinite(num(v)))return num(v);const s=String(v||'');const h=s.match(/(\d+(?:\.\d+)?)\s*h/i),m=s.match(/(\d+(?:\.\d+)?)\s*m/i);return h?num(h[1])+(m?num(m[1])/60:0):NaN}
function windowValue(obj,key,w){if(obj===null||obj===undefined)return NaN;if(typeof obj==='object'&&!Array.isArray(obj)){const v=pick(obj,[w,w.replace('m','min')]);if(v!==undefined)return num(v)}return num(obj)}
function tokenMarketCap(o){const direct=num(pick(o,['market_cap','marketCap','fdv']));if(Number.isFinite(direct))return direct;const xs=num(o?.token_x?.market_cap),ys=num(o?.token_y?.market_cap);return Number.isFinite(xs)&&Number.isFinite(ys)?Math.max(xs,ys):Number.isFinite(xs)?xs:Number.isFinite(ys)?ys:NaN}
function createdAge(o){const raw=pick(o,['age_hours','ageHours','age','token_age']);const direct=hours(raw);if(Number.isFinite(direct))return direct;const ts=num(o?.created_at);if(Number.isFinite(ts)&&ts>0)return Math.max(0,(Date.now()/1000-ts)/3600);return NaN}
function normalize(o){const w=state.window,n=o.metrics||o.stats||{};
  const tvl=num(pick(o,['active_tvl','activeTvl','active_liquidity'],pick(n,['active_tvl','activeTvl'])));
  const totalTvl=num(pick(o,['tvl','total_tvl','liquidity'],pick(n,['tvl','total_tvl'])));
  const baseTvl=Number.isFinite(tvl)?tvl:totalTvl;
  const feeObj=pick(o,['fees'],pick(n,['fees']));
  const volObj=pick(o,['volume'],pick(n,['volume']));
  const ratioObj=pick(o,['fee_tvl_ratio','fees_active_tvl','fees_over_active_tvl','fees_per_active_tvl'],pick(n,['fee_tvl_ratio']));
  const fees=windowValue(feeObj,w);
  const volume=windowValue(volObj,w);
  let feeRatio=windowValue(ratioObj,w);
  if(!Number.isFinite(feeRatio)&&fees>0&&baseTvl>0)feeRatio=fees/baseTvl*100;
  let volRatio=volume>0&&baseTvl>0?volume/baseTvl*100:NaN;
  const address=pick(o,['address','pool_address','public_key','publicKey'],''),name=pick(o,['name','pool_name','symbol','pair'],'Unknown');
  const mc=tokenMarketCap(o),age=createdAge(o);
  const directPrice=num(pick(o,[`${w}_price_change`,`price_change_${w}`,`${w}_price_change_pct`,`price_change`,'priceChange']));
  const currentPrice=num(pick(o,['current_price','price']));
  return {raw:o,name,address,tvl:baseTvl,totalTvl:Number.isFinite(totalTvl)?totalTvl:baseTvl,fees,volume,feeRatio,volRatio,mc,age,price:directPrice,currentPrice,tvlFallback:!Number.isFinite(tvl)}
}
function historyKey(p){return p.address||p.name}
function updateLocalHistory(){const now=Date.now();for(const p of state.pools.map(normalize)){const k=historyKey(p);if(!k)continue;const arr=state.history[k]||[];arr.push({t:now,fee:p.feeRatio,vol:p.volRatio,tvl:p.tvl,price:p.price});state.history[k]=arr.slice(-30)};localStorage.setItem('dlmmRadarHistory',JSON.stringify(state.history))}
function localStability(p){const arr=state.history[historyKey(p)]||[];if(arr.length<3)return 45;const fees=arr.map(x=>x.fee).filter(Number.isFinite),vols=arr.map(x=>x.vol).filter(Number.isFinite),prices=arr.map(x=>x.price).filter(Number.isFinite);const cv=(a)=>{if(a.length<2)return .8;const m=a.reduce((x,y)=>x+y,0)/a.length;const sd=Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length);return m?sd/Math.abs(m):1};const feeSt=clamp(100-cv(fees)*55,0,100),volSt=clamp(100-cv(vols)*45,0,100),priceSt=prices.length?clamp(100-Math.abs(prices[prices.length-1])*1.8,0,100):50;return feeSt*.4+volSt*.3+priceSt*.3}
function continuity(series){const a=series.filter(Number.isFinite);if(a.length<3)return 45;const positive=a.filter(x=>x>0).length/a.length;const m=a.reduce((s,x)=>s+x,0)/a.length;const sd=Math.sqrt(a.reduce((s,x)=>s+(x-m)**2,0)/a.length);const cv=m?sd/Math.abs(m):2;const consistency=clamp(100-cv*55,0,100);return clamp(positive*55+consistency*.45,0,100)}
function apiHistoryScore(p){const h=state.apiHistory[historyKey(p)];if(!h?.volume?.length)return {score:45,confidence:0,coverage:0,drawdown:NaN,volatility:NaN};const fees=h.volume.map(x=>num(x.fees)).filter(Number.isFinite),vols=h.volume.map(x=>num(x.volume)).filter(Number.isFinite);const feeCont=continuity(fees),volCont=continuity(vols);let drawdown=NaN,volatility=NaN,priceSt=50;
  if(h.ohlcv?.length){const closes=h.ohlcv.map(x=>num(x.close)).filter(Number.isFinite);if(closes.length){let peak=closes[0],maxDD=0;closes.forEach(c=>{peak=Math.max(peak,c);if(peak>0)maxDD=Math.max(maxDD,(peak-c)/peak)});drawdown=maxDD*100;const returns=[];for(let i=1;i<closes.length;i++)if(closes[i-1]>0)returns.push((closes[i]-closes[i-1])/closes[i-1]*100);if(returns.length){const m=returns.reduce((s,x)=>s+x,0)/returns.length;volatility=Math.sqrt(returns.reduce((s,x)=>s+(x-m)**2,0)/returns.length)}priceSt=clamp(100-drawdown*2.2-volatility*1.5,0,100)}}
  const score=feeCont*.4+volCont*.3+priceSt*.3;const confidence=clamp((h.volume.length/24)*70+(h.ohlcv?.length||0)/24*30,0,100);return {score,confidence,coverage:Math.min(fees.length,vols.length),drawdown,volatility,feeCont,volCont}}
function effectiveStability(p){const h=apiHistoryScore(p);return h.confidence>=35?h.score:localStability(p)}
function scoreParts(p){const stabilityScore=effectiveStability(p),fee=clamp((Math.log10(Math.max(p.feeRatio,.01))+2)/3.2*100,0,100),vol=clamp(Math.log10(Math.max(p.volRatio,1))/4*100,0,100),tvl=clamp((Math.log10(Math.max(p.tvl,1000))-3)/3*100,0,100),abs=Math.abs(p.price||0),price=Number.isFinite(p.price)?(abs<=5?100:abs<=10?88:abs<=15?72:abs<=25?48:abs<=40?25:5):50,age=Number.isFinite(p.age)?clamp((Math.log10(Math.max(p.age,1))+.3)/2.7*100,0,100):35,mc=Number.isFinite(p.mc)?clamp((Math.log10(Math.max(p.mc,1))-4)/4*100,0,100):35;return {fee,vol,tvl,price,age,mc,stability:stabilityScore}}
function score(p){const w=state.weights[state.mode],v=scoreParts(p),total=Object.values(w).reduce((a,b)=>a+b,0);return Object.keys(w).reduce((s,k)=>s+v[k]*w[k],0)/total}
function signal(p,s){const flags=[];const h=apiHistoryScore(p);if(p.age<6)flags.push('çok yeni');if(p.tvl<10000)flags.push('ince likidite');if(Number.isFinite(p.price)&&Math.abs(p.price)>25)flags.push('sert fiyat hareketi');if(p.feeRatio>15)flags.push('aşırı fee oranı');if(Number.isFinite(p.totalTvl)&&p.totalTvl>p.tvl*5)flags.push('aktif TVL düşük');if(state.mode==='multiday'&&h.confidence>=35&&h.score<45)flags.push('geçmiş fee/hacim zayıf');if(h.confidence>=35&&Number.isFinite(h.drawdown)&&h.drawdown>35)flags.push('24h drawdown yüksek');const txt=s>=80?'Güçlü aday':s>=60?'İncele':'Temkinli',cls=s>=80?'good':s>=60?'mid':'bad';return [txt,cls,flags]}
function filtered(){const q=$('search').value.trim().toLowerCase(),minT=num($('minTvl').value)||0,minA=num($('minAge').value)||0,pf=$('priceFilter').value;return state.pools.map(normalize).filter(p=>(!q||p.name.toLowerCase().includes(q)||p.address.toLowerCase().includes(q))&&(!Number.isFinite(p.tvl)||p.tvl>=minT)&&(!Number.isFinite(p.age)||p.age>=minA)&&(pf==='all'||(pf==='stable'&&Math.abs(p.price||0)<=15)||(pf==='up'&&(p.price||0)>0)||(pf==='down'&&(p.price||0)<0))).map(p=>({...p,score:score(p),stability:effectiveStability(p),history:apiHistoryScore(p)})).sort((a,b)=>b.score-a.score)}
function strategyInfo(){const multi=state.mode==='multiday';$('strategyInfo').innerHTML=multi?`<div><b>🟢 Multiday LP</b><span> Amaç: birkaç gün boyunca sürekli takip gerektirmeden daha dengeli fee üretimi aramak.</span></div><div class="strategy-points"><span>↑ Fee/Active TVL</span><span>↑ Volume/Active TVL</span><span>↑ TVL</span><span>↑ Yaş</span><span>↑ tarihsel süreklilik</span><span>↓ fiyat drawdown</span></div>`:`<div><b>🟠 Yeni / Yüksek Risk</b><span> Amaç: yeni havuzlarda yüksek fee ve hacim oluşan fırsatları erken yakalamak.</span></div><div class="strategy-points"><span>↑ Fee/Active TVL</span><span>↑ Volume/Active TVL</span><span>↑ yeni aktivite</span><span>↑ yeterli TVL</span><span>⚠ tarihsel veri oluştuğunda süreklilik kontrolü</span></div>`}
function historyBadge(h){if(h.confidence>=70)return `<span class="history good">${h.score.toFixed(0)} · güçlü veri</span>`;if(h.confidence>=35)return `<span class="history mid">${h.score.toFixed(0)} · kısmi</span>`;return `<span class="history neutral">Bekleniyor</span>`}
function render(){strategyInfo();const rows=filtered();$('countText').textContent=`${rows.length} havuz`;$('poolBody').innerHTML=rows.map(p=>{const [txt,cls]=signal(p,p.score),sc=p.score>=80?'good':p.score>=60?'mid':'bad';const h=p.history;return `<tr><td><span class="score ${sc}">${p.score.toFixed(0)}</span></td><td><div class="pool"><span class="coin">${escapeHtml(p.name.slice(0,2).toUpperCase())}</span><div><div class="pool-name">${escapeHtml(p.name)}</div><div class="pool-sub">${escapeHtml(p.address?p.address.slice(0,6)+'…'+p.address.slice(-4):'')}</div></div></div></td><td>${Number.isFinite(p.age)?p.age.toFixed(1)+'h':'—'}</td><td>${fmtUSD(p.mc)}</td><td>${fmtUSD(p.tvl)}${p.tvlFallback?' <span class="pool-sub">TVL</span>':''}</td><td>${fmtUSD(p.fees)}</td><td class="${p.feeRatio>=5?'positive':''}">${Number.isFinite(p.feeRatio)?p.feeRatio.toFixed(2)+'%':'—'}</td><td class="${p.volRatio>=500?'positive':''}">${Number.isFinite(p.volRatio)?p.volRatio.toFixed(0)+'%':'—'}</td><td class="${p.price>0?'positive':p.price<0?'negative':'neutral'}">${fmtPct(p.price)}</td><td>${historyBadge(h)}</td><td><span class="signal ${cls}">${txt}</span>${signal(p,p.score)[2].length?`<div class="pool-sub">${signal(p,p.score)[2].join(' • ')}</div>`:''}</td></tr>`}).join('');const good=rows.filter(x=>x.score>=80).length,avg=rows.length?rows.reduce((a,b)=>a+b.score,0)/rows.length:0,maxFee=rows.reduce((m,x)=>Math.max(m,Number.isFinite(x.feeRatio)?x.feeRatio:0),0);$('summary').innerHTML=`<div class="card stat"><div class="label">Görünen havuz</div><div class="value">${rows.length}</div><div class="sub">filtrelerden sonra</div></div><div class="card stat"><div class="label">80+ aday</div><div class="value">${good}</div><div class="sub">seçili strateji</div></div><div class="card stat"><div class="label">Ortalama skor</div><div class="value">${avg.toFixed(0)}</div><div class="sub">0–100</div></div><div class="card stat"><div class="label">Tarihsel veri</div><div class="value">${rows.filter(x=>x.history.confidence>=35).length}</div><div class="sub">yeterli geçmiş bulunan</div></div>`;const warnings=[];rows.slice(0,10).forEach(p=>{const f=signal(p,p.score)[2];if(f.length)warnings.push(`<li><b>${escapeHtml(p.name)}</b>: ${f.join(', ')}</li>`)});$('warnings').innerHTML=warnings.length?warnings.join(''):'<li>Seçili filtrelerde belirgin uyarı yok.</li>';renderGuide();$('historyStatus').textContent=state.historyLoading?'Tarihsel veriler getiriliyor…':`Tarihsel kontrol: ${Object.values(state.apiHistory).filter(x=>x?.fetchedAt&&Date.now()-x.fetchedAt<HISTORY_TTL).length} havuz önbellekte`}
function renderGuide(){const multi=state.mode==='multiday';$('scoreGuide').innerHTML=multi?`<div class="rule"><b>25%</b><div><strong>Fees / Active TVL</strong><p>Fee verimliliği yüksek olmalı.</p></div></div><div class="rule"><b>15%</b><div><strong>Volume / Active TVL</strong><p>Fee'nin gerçek işlem aktivitesiyle desteklenmesi aranır.</p></div></div><div class="rule"><b>15%</b><div><strong>TVL</strong><p>Çok küçük likidite havuzlarını sınırlar. Meteora API'sinde Active TVL yoksa toplam TVL kullanılır.</p></div></div><div class="rule"><b>15%</b><div><strong>Fiyat istikrarı</strong><p>24 saatlik geçmiş veride drawdown ve oynaklık arttıkça puanı düşürür.</p></div></div><div class="rule"><b>15%</b><div><strong>Token yaşı</strong><p>Multiday için geçmişi olan havuzları öne çıkarır.</p></div></div><div class="rule"><b>10%</b><div><strong>Tarihsel süreklilik</strong><p>Son 24 saatte fee ve hacmin kaç saat/bucket boyunca üretildiğini ölçer. Kısa spike'ları zayıflatır.</p></div></div>`:`<div class="rule"><b>30%</b><div><strong>Fees / Active TVL</strong><p>Yeni fırsatlarda yüksek fee üretimini öne çıkarır.</p></div></div><div class="rule"><b>30%</b><div><strong>Volume / Active TVL</strong><p>Hacim patlamalarını yakalar.</p></div></div><div class="rule"><b>10%</b><div><strong>TVL</strong><p>Çok ince likiditeyi sınırlamak için kullanılır.</p></div></div><div class="rule"><b>10%</b><div><strong>Fiyat</strong><p>Aşırı hareketleri tamamen görmezden gelmez.</p></div></div><div class="rule"><b>5%</b><div><strong>Yaş</strong><p>Yeni havuzları cezalandırır ama multiday kadar sert değildir.</p></div></div><div class="rule"><b>10%</b><div><strong>Tarihsel süreklilik</strong><p>Geçmiş veri oluştuğunda fee/hacim üretiminin sürekliliğini kontrol eder.</p></div></div>`}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function setStatus(t,ok=true){$('statusText').textContent=t;$('statusBox').querySelector('.dot').style.background=ok?'var(--green)':'var(--red)'}
async function fetchJson(url){const r=await fetch(url,{headers:{accept:'application/json'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return r.json()}
async function mapLimit(items,limit,worker){const out=new Array(items.length);let next=0;async function run(){while(true){const i=next++;if(i>=items.length)return;try{out[i]=await worker(items[i],i)}catch(e){out[i]={error:e.message}}}}await Promise.all(Array.from({length:Math.min(limit,items.length)},run));return out}
function historyTimeframe(){return '1h'}
async function loadPoolHistory(pool,force=false){const k=historyKey(pool);if(!k)return;const old=state.apiHistory[k];if(!force&&old?.fetchedAt&&Date.now()-old.fetchedAt<HISTORY_TTL)return;const tf=historyTimeframe();const end=Math.floor(Date.now()/1000),start=end-24*3600;const base=`${API}/pools/${encodeURIComponent(pool.address)}`;const [v,o]=await Promise.all([fetchJson(`${base}/volume/history?timeframe=${tf}&start_time=${start}&end_time=${end}`),fetchJson(`${base}/ohlcv?timeframe=${tf}&start_time=${start}&end_time=${end}`)]);state.apiHistory[k]={fetchedAt:Date.now(),timeframe:tf,volume:Array.isArray(v?.data)?v.data:[],ohlcv:Array.isArray(o?.data)?o.data:[]}}
async function enrichHistory(){if(!state.pools.length||state.historyLoading)return;const candidates=filtered().slice(0,state.mode==='multiday'?30:20);const need=candidates.filter(p=>p.address&&!state.apiHistory[historyKey(p)]?.fetchedAt||Date.now()-state.apiHistory[historyKey(p)].fetchedAt>=HISTORY_TTL);if(!need.length){render();return}state.historyLoading=true;render();setStatus(`Tarihsel veri getiriliyor… 0/${need.length}`);let done=0;await mapLimit(need,5,async p=>{try{await loadPoolHistory(p);done++;setStatus(`Tarihsel veri getiriliyor… ${done}/${need.length}`);render()}catch(e){done++;console.warn('History',p.name,e);setStatus(`Tarihsel veri: ${done}/${need.length} • bazı havuzlar alınamadı`,false)}});state.historyLoading=false;localStorage.setItem('dlmmRadarApiHistory',JSON.stringify(state.apiHistory));setStatus(`Güncellendi • ${new Date().toLocaleTimeString('tr-TR')}`);render()}
async function fetchPools(){setStatus('Meteora API okunuyor…');const w=state.window,url=`${POOLS_API}?page=1&page_size=1000&sort_by=fee_${w}:desc&filter_by=is_blacklisted=false`;try{const j=await fetchJson(url),arr=Array.isArray(j)?j:(j.data||j.pools||j.items||[]);if(!arr.length)throw Error('API veri döndürmedi');state.pools=arr;updateLocalHistory();localStorage.setItem('dlmmRadarPools',JSON.stringify(arr));setStatus(`Güncellendi • ${new Date().toLocaleTimeString('tr-TR')}`);render();await enrichHistory()}catch(e){console.warn(e);setStatus('Canlı API erişilemedi; yerel veri kullanılabilir',false);const saved=localStorage.getItem('dlmmRadarPools');if(saved){try{state.pools=JSON.parse(saved);render()}catch{}}}}
function demo(){state.pools=[{name:'P(DOOM)-SOL',age:'3h 29m',market_cap:637560,active_tvl:13630,tvl:14850,fees:{'2h':3810},volume:{'2h':280000},price_change:-2.1},{name:'KARDASHEV-SOL 1%',age:'4h 55m',market_cap:1560000,active_tvl:39570,tvl:39540,fees:{'2h':2120},volume:{'2h':190000},price_change:-12.13},{name:'KARDASHEV-SOL 3%',age:'4h 55m',market_cap:1560000,active_tvl:63170,tvl:67960,fees:{'2h':4080},volume:{'2h':340000},price_change:-13.87},{name:'YAP-SOL',age:'22h 10m',market_cap:4210000,active_tvl:191060,tvl:189880,fees:{'2h':8780},volume:{'2h':1300000},price_change:103},{name:'DDOS-SOL',age:'7h 40m',market_cap:427810,active_tvl:21460,tvl:23220,fees:{'2h':1920},volume:{'2h':240000},price_change:-52.11}];updateLocalHistory();setStatus('Örnek veri');render()}
const weightFields=[['fee','Fees / Active TVL'],['vol','Volume / Active TVL'],['tvl','TVL'],['price','Fiyat istikrarı'],['age','Token yaşı'],['mc','Market cap'],['stability','Tarihsel süreklilik']];
function buildWeights(){for(const [container,mode] of [['multiWeights','multiday'],['riskWeights','newrisk']]){$(container).innerHTML=weightFields.map(([k,l])=>`<label>${l} <output id="${mode}_${k}Out">${state.weights[mode][k]}</output>%<input id="${mode}_${k}" type="range" min="0" max="50" value="${state.weights[mode][k]}" /></label>`).join('');for(const [k] of weightFields)$(mode+'_'+k).addEventListener('input',checkWeights)}}
function checkWeights(){let ok=true,total=[];for(const mode of ['multiday','newrisk']){const t=weightFields.reduce((s,[k])=>{const el=$(mode+'_'+k),v=Number(el.value);$(mode+'_'+k+'Out').value=v;return s+v},0);total.push(`${mode==='multiday'?'Multiday':'Yeni/Risk'}: ${t}%`);if(t!==100)ok=false}$('weightTotal').textContent=total.join(' • ')+(ok?' ✓':' — her biri 100 olmalı');$('weightTotal').className='weight-total '+(ok?'ok':'bad');return ok}
function bind(){document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{document.querySelectorAll('.mode').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.mode=b.dataset.mode;render();enrichHistory()});['search','minTvl','minAge','priceFilter'].forEach(id=>$(id).addEventListener('input',render));$('window').addEventListener('change',()=>{state.window=$('window').value;fetchPools()});$('refreshBtn').onclick=fetchPools;$('demoBtn').onclick=demo;$('settingsBtn').onclick=()=>{$('settingsDialog').showModal()};$('loadJsonBtn').onclick=()=>{try{const j=JSON.parse($('jsonInput').value),arr=Array.isArray(j)?j:(j.data||j.pools||j.items||[]);if(!arr.length)throw Error('Dizi bulunamadı');state.pools=arr;updateLocalHistory();localStorage.setItem('dlmmRadarPools',JSON.stringify(arr));setStatus(`Manuel veri yüklendi • ${arr.length} havuz`);render();enrichHistory()}catch(e){alert('JSON okunamadı: '+e.message)}};$('copyPromptBtn').onclick=()=>{navigator.clipboard?.writeText('{"data":[{"name":"TOKEN-SOL","address":"...","age_hours":24,"market_cap":1000000,"active_tvl":50000,"tvl":70000,"fees_2h":3000,"volume_2h":150000,"price_change_2h":-4.5}]}');alert('Şablon panoya kopyalandı.');};$('saveWeights').onclick=e=>{e.preventDefault();if(!checkWeights())return;for(const mode of ['multiday','newrisk'])for(const [k] of weightFields)state.weights[mode][k]=Number($(mode+'_'+k).value);localStorage.setItem('dlmmRadarWeights',JSON.stringify(state.weights));$('settingsDialog').close();render()};buildWeights();checkWeights()}
bind();try{const h=localStorage.getItem('dlmmRadarHistory');if(h)state.history=JSON.parse(h);const ah=localStorage.getItem('dlmmRadarApiHistory');if(ah)state.apiHistory=JSON.parse(ah);const w=localStorage.getItem('dlmmRadarWeights');if(w)state.weights=JSON.parse(w)}catch{}const saved=localStorage.getItem('dlmmRadarPools');if(saved){try{state.pools=JSON.parse(saved);render()}catch{}}else demo();fetchPools();
